language: go

go:
  - master

script:
  - ./run_test.sh

after_success:
  - include_cov=coverage.txt bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      secure: "P+9YnouQgpKEFDgVeDkwMWgX6HQ2sHKBmhEYIjw5HuymrolOeCtLZwqCgjEcTQV8itq60Y4lyqzZBH73/MXYMZzF0yDZVW/GicjdyA6CshhX0jpw/3mvF8n0niLb/tUAFfBFR8pKkGe5PBxTej01kdQd/VJ2dYh5VCrihzl86lIj2J6YhEmthjrPrqapDY+rl79pzJPnAE9TVYZEwg/pbiVlY5jpAUJkjcJVBuI0xA1q0qwtXotvFW496T0QZa8WKPB9oSl9LcKlA/6xwVqj6Lby2JKHWX8ur0SsGF5xAMO9calLHfuZnz38+q7KDMEVsrDvl+exwuqSVlFKr45mKfXlH+bDeAY/fkUtGlQBUlriyBxwcThwFMjNnXbFt7jfOUkfbIuCrup0+8xq08UkK7tYqVyYtpirh3XZ15BHcYdyWBvtRnpn0KzTDLsJvAVSZmlYIuD3DhWFbQCFVjIaNvfmb29fYSF2mqP5YBVdaRyWcwV+rdKPtDgriZ0CJdARn7Gy2bj0cGKpm+3nFZF2Wo/XOcuqj5XNEhIyEmrks0hc7+XZzEY93fYNJcehDcJWgXcmQXdY+zWzNQqH4y2cn0M1tDiz2BzxW599pe5t0JTWy74e9vCPzOm7ze/Ymib8YzN/Fcl4rOF4t5IHtRFMDnlmy7PdOXSLc5eT2SVOruo="
    on_success: change
    on_failure: always
